databases:
  - name: moodify-db
    plan: free
    databaseName: moodify
    user: moodify_user

services:
  - type: web
    name: moodify-backend
    runtime: docker
    plan: free
    rootDir: moodify-backend
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: moodify-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: moodify-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: moodify-db
          property: database
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: moodify-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: moodify-db
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: GEMINI_API_KEY
        value: AIzaSyAFcfkuun-qYGRBv2M9TnmwuZ5Rx5TQHQk
      - key: FRONTEND_URL
        value: https://moodify-frontend.onrender.com

  - type: web
    name: moodify-frontend
    runtime: static
    rootDir: moodify-frontend
    buildCommand: npm install && ./node_modules/.bin/vite build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://moodify-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
